# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deadlift', models.FloatField(default='0')),
                ('oh_press', models.FloatField(default='0')),
                ('barbell_row', models.FloatField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bench_press', models.FloatField(default='0')),
                ('squat', models.FloatField(default='0')),
                ('pull_ups', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlift', models.FloatField(default='20')),
                ('oh_press', models.FloatField(default='20')),
                ('barbell_row', models.FloatField(default='20')),
                ('bench_press', models.FloatField(default='20')),
                ('squat', models.FloatField(default='20')),
                ('pull_ups', models.IntegerField(default='max')),
                ('last_training', models.CharField(choices=[('A', 'Dzień A'), ('B', 'Dzień B')], max_length=1)),
                ('training_count', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
