# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifts',
            name='barbell_row',
            field=models.FloatField(default='20'),
        ),
        migrations.AlterField(
            model_name='lifts',
            name='bench_press',
            field=models.FloatField(default='20'),
        ),
        migrations.AlterField(
            model_name='lifts',
            name='deadlift',
            field=models.FloatField(default='20'),
        ),
        migrations.AlterField(
            model_name='lifts',
            name='oh_press',
            field=models.FloatField(default='20'),
        ),
        migrations.AlterField(
            model_name='lifts',
            name='squat',
            field=models.FloatField(default='20'),
        ),
    ]
