# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0002_auto_20171219_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifts',
            name='last_training',
            field=models.CharField(choices=[('A', 'Dzień A'), ('B', 'Dzień B')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
